export type TravelCategory = "Lived" | "Worked" | "Visited";

export type TravelPlace = {
  name: string;
  country: string;
  continent: string;
  category: TravelCategory;
  lat: number;
  lng: number;
  image?: string;
  note: string;
};

export type TravelPhoto = {
  src: string;
  title: string;
  country: string;
};

export const travelGallery: TravelPhoto[] = [
  { src: "/images/travel/SDG.webp", title: "Sadalaga", country: "India" },
  { src: "/images/travel/RBD_4.webp", title: "Kolhapur", country: "India" },
  { src: "/images/travel/IITM.webp", title: "IIT Madras", country: "India" },
  { src: "/images/travel/IITR.webp", title: "IIT Roorkee", country: "India" },
  { src: "/images/travel/Vadodara.webp", title: "Vadodara", country: "India" },
  { src: "/images/travel/Delhi.webp", title: "Delhi", country: "India" },
  { src: "/images/travel/Mahabalipuram_1.webp", title: "Mahabalipuram", country: "India" },
  { src: "/images/travel/Badami.webp", title: "Badami", country: "India" },
  { src: "/images/travel/Aihole.webp", title: "Aihole", country: "India" },
  { src: "/images/travel/Patadkal.webp", title: "Pattadakal", country: "India" },
  { src: "/images/travel/Athirapalli_1.webp", title: "Athirapalli", country: "India" },
  { src: "/images/travel/Kanyakumari.webp", title: "Kanyakumari", country: "India" },
  { src: "/images/travel/Mumbai.webp", title: "Mumbai", country: "India" },
  { src: "/images/travel/Dresden.webp", title: "Dresden", country: "Germany" },
  { src: "/images/travel/Pinneberg.webp", title: "Pinneberg", country: "Germany" },
  { src: "/images/travel/Berlin.webp", title: "Berlin", country: "Germany" },
  { src: "/images/travel/Prague.webp", title: "Prague", country: "Czech Republic" },
  { src: "/images/travel/Vienna_1.webp", title: "Vienna", country: "Austria" },
  { src: "/images/travel/Bratislava.webp", title: "Bratislava", country: "Slovakia" },
  { src: "/images/travel/Krakow.webp", title: "Krakow", country: "Poland" },
  { src: "/images/travel/Auschwitz.webp", title: "Auschwitz-Birkenau", country: "Poland" },
  { src: "/images/travel/zakopane.webp", title: "Zakopane", country: "Poland" },
  { src: "/images/travel/Tallin_1.webp", title: "Tallinn", country: "Estonia" },
  { src: "/images/travel/Copenhagen.webp", title: "Copenhagen", country: "Denmark" },
  { src: "/images/travel/Oslo.webp", title: "Oslo", country: "Norway" },
  { src: "/images/travel/Tromso.webp", title: "Tromso", country: "Norway" },
  { src: "/images/travel/Lucerne.webp", title: "Lucerne", country: "Switzerland" },
  { src: "/images/travel/Switzerland.webp", title: "Mount Pilatus", country: "Switzerland" },
  { src: "/images/travel/Paris.webp", title: "Paris", country: "France" },
  { src: "/images/travel/Versailles.webp", title: "Versailles", country: "France" },
  { src: "/images/travel/Mont_Saint_Michel.webp", title: "Mont Saint-Michel", country: "France" },
  { src: "/images/travel/Rome.webp", title: "Rome", country: "Italy" },
  { src: "/images/travel/Florence.webp", title: "Florence", country: "Italy" },
  { src: "/images/travel/Vatican.webp", title: "Vatican City", country: "Vatican City" },
  { src: "/images/travel/Dubai.webp", title: "Dubai", country: "United Arab Emirates" },
  { src: "/images/travel/liberty.webp", title: "New York", country: "United States" },
  { src: "/images/travel/Washington.webp", title: "Washington, DC", country: "United States" },
  { src: "/images/travel/Hoboken.webp", title: "Hoboken", country: "United States" },
];

export const travelPlaces: TravelPlace[] = [
  {
    name: "Sadalaga",
    country: "India",
    continent: "Asia",
    category: "Lived",
    lat: 16.5533,
    lng: 74.5317,
    image: "/images/travel/SDG.webp",
    note: "Hometown and long-term anchor in northern Karnataka.",
  },
  {
    name: "Kolhapur",
    country: "India",
    continent: "Asia",
    category: "Lived",
    lat: 16.691307,
    lng: 74.244865,
    image: "/images/travel/RBD_4.webp",
    note: "A frequent base connected to family, study, and travel across western India.",
  },
  {
    name: "Surat",
    country: "India",
    continent: "Asia",
    category: "Worked",
    lat: 21.1702401,
    lng: 72.8310607,
    image: "/images/travel/Vadodara.webp",
    note: "Master's studies and an important early academic chapter.",
  },
  {
    name: "Chennai",
    country: "India",
    continent: "Asia",
    category: "Worked",
    lat: 13.0826802,
    lng: 80.2707184,
    image: "/images/travel/Mahabalipuram_1.webp",
    note: "PhD years and long-form research work at IIT Madras.",
  },
  {
    name: "Delhi",
    country: "India",
    continent: "Asia",
    category: "Worked",
    lat: 28.7040592,
    lng: 77.1024902,
    image: "/images/travel/Delhi.webp",
    note: "Research collaboration and fieldwork linked to CRRI.",
  },
  {
    name: "Dresden",
    country: "Germany",
    continent: "Europe",
    category: "Worked",
    lat: 51.0504088,
    lng: 13.7372621,
    image: "/images/travel/Dresden.webp",
    note: "Postdoctoral work in transport modeling and urban systems.",
  },
  {
    name: "Hamburg",
    country: "Germany",
    continent: "Europe",
    category: "Worked",
    lat: 53.5488282,
    lng: 9.9871703,
    image: "/images/travel/Cuxhaven.webp",
    note: "Teaching, mentoring, and current professional base in northern Germany.",
  },
  {
    name: "Pinneberg",
    country: "Germany",
    continent: "Europe",
    category: "Lived",
    lat: 53.6545225,
    lng: 9.7938212,
    image: "/images/travel/Pinneberg.webp",
    note: "A quieter residential stop close to Hamburg.",
  },
  {
    name: "Mysuru",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 12.29581,
    lng: 76.639381,
    image: "/images/travel/Mysuru.webp",
    note: "One of the recurring southern India trips in the travel archive.",
  },
  {
    name: "Mumbai",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 19.076,
    lng: 72.8777,
    image: "/images/travel/Mumbai.webp",
    note: "Major city stop with repeated academic and personal travel.",
  },
  {
    name: "Bhopal",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 23.2573,
    lng: 77.4022,
    image: "/images/travel/Bhopal.webp",
    note: "Central India visit represented in the older travel map.",
  },
  {
    name: "Ujjain",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 23.1772,
    lng: 75.7829,
    image: "/images/travel/Ujjain.webp",
    note: "Historic city stop from the Madhya Pradesh travel cluster.",
  },
  {
    name: "Badami",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 15.9186,
    lng: 75.6761,
    image: "/images/travel/Badami.webp",
    note: "A memorable heritage and architecture trip in Karnataka.",
  },
  {
    name: "Aihole",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 16.0198,
    lng: 75.881,
    image: "/images/travel/Aihole.webp",
    note: "One of the historic temple-site visits captured in the archive.",
  },
  {
    name: "Pattadakal",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 15.9488,
    lng: 75.8164,
    image: "/images/travel/Patadkal.webp",
    note: "UNESCO heritage stop connected to the Badami-Aihole circuit.",
  },
  {
    name: "Frankfurt",
    country: "Germany",
    continent: "Europe",
    category: "Visited",
    lat: 50.1109,
    lng: 8.6821,
    image: "/images/travel/Frankfurt.webp",
    note: "A frequent transit and city visit in Germany.",
  },
  {
    name: "Berlin",
    country: "Germany",
    continent: "Europe",
    category: "Visited",
    lat: 52.52,
    lng: 13.405,
    image: "/images/travel/Berlin.webp",
    note: "Regular travel to the capital for events, meetings, and exploring.",
  },
  {
    name: "Prague",
    country: "Czech Republic",
    continent: "Europe",
    category: "Visited",
    lat: 50.0755,
    lng: 14.4378,
    image: "/images/travel/Prague.webp",
    note: "A central Europe trip from the broader travel map.",
  },
  {
    name: "Vienna",
    country: "Austria",
    continent: "Europe",
    category: "Visited",
    lat: 48.210033,
    lng: 16.363449,
    image: "/images/travel/Vienna_1.webp",
    note: "City break and cultural stop in Austria.",
  },
  {
    name: "Bratislava",
    country: "Slovakia",
    continent: "Europe",
    category: "Visited",
    lat: 48.148598,
    lng: 17.107748,
    image: "/images/travel/Bratislava.webp",
    note: "A short but memorable stop paired with nearby central Europe travel.",
  },
  {
    name: "Paris",
    country: "France",
    continent: "Europe",
    category: "Visited",
    lat: 48.864716,
    lng: 2.349014,
    image: "/images/travel/Paris.webp",
    note: "Classic city visit from the western Europe stretch of the map.",
  },
  {
    name: "Mont Saint-Michel",
    country: "France",
    continent: "Europe",
    category: "Visited",
    lat: 48.636002,
    lng: -1.5114,
    image: "/images/travel/Mont_Saint_Michel.webp",
    note: "A standout destination from the France itinerary.",
  },
  {
    name: "Rome",
    country: "Italy",
    continent: "Europe",
    category: "Visited",
    lat: 41.89193,
    lng: 12.51133,
    image: "/images/travel/Rome.webp",
    note: "A major stop in the Italy travel set.",
  },
  {
    name: "Florence",
    country: "Italy",
    continent: "Europe",
    category: "Visited",
    lat: 43.769562,
    lng: 11.255814,
    image: "/images/travel/Florence.webp",
    note: "Historic architecture, museums, and street life in Tuscany.",
  },
  {
    name: "Pisa",
    country: "Italy",
    continent: "Europe",
    category: "Visited",
    lat: 43.716667,
    lng: 10.4,
    image: "/images/travel/Pisa.webp",
    note: "Part of the broader Italy route documented in the gallery.",
  },
  {
    name: "Vatican City",
    country: "Vatican City",
    continent: "Europe",
    category: "Visited",
    lat: 41.9029,
    lng: 12.4534,
    image: "/images/travel/Vatican.webp",
    note: "A compact but iconic stop during the Rome visit.",
  },
  {
    name: "Copenhagen",
    country: "Denmark",
    continent: "Europe",
    category: "Visited",
    lat: 55.676098,
    lng: 12.568337,
    image: "/images/travel/Copenhagen.webp",
    note: "Nordic city visit represented in the travel archive.",
  },
  {
    name: "Lund",
    country: "Sweden",
    continent: "Europe",
    category: "Visited",
    lat: 55.7047,
    lng: 13.191,
    image: "/images/travel/Lund.webp",
    note: "A nearby university city stop during Scandinavian travel.",
  },
  {
    name: "Oslo",
    country: "Norway",
    continent: "Europe",
    category: "Visited",
    lat: 59.91273,
    lng: 10.74609,
    image: "/images/travel/Oslo.webp",
    note: "One of the northern Europe routes in the travel collection.",
  },
  {
    name: "Tromso",
    country: "Norway",
    continent: "Europe",
    category: "Visited",
    lat: 69.650253,
    lng: 18.995115,
    image: "/images/travel/Tromso.webp",
    note: "A far north trip that adds real geographic range to the map.",
  },
  {
    name: "Dubai",
    country: "United Arab Emirates",
    continent: "Asia",
    category: "Visited",
    lat: 25.2048,
    lng: 55.2708,
    image: "/images/travel/Dubai.webp",
    note: "Short international stopover and city visit in the Gulf.",
  },
  {
    name: "New York",
    country: "United States",
    continent: "North America",
    category: "Visited",
    lat: 40.6892,
    lng: -74.0445,
    image: "/images/travel/liberty.webp",
    note: "A memorable US visit anchored around New York harbor.",
  },
  {
    name: "Washington, DC",
    country: "United States",
    continent: "North America",
    category: "Visited",
    lat: 38.9072,
    lng: -77.0369,
    image: "/images/travel/Washington.webp",
    note: "Another major stop from the US leg of the map.",
  },
  {
    name: "Bhuinj",
    country: "India",
    continent: "Asia",
    category: "Lived",
    lat: 17.876184,
    lng: 73.96978,
    image: "/images/travel/RBD_4.webp",
    note: "A Maharashtra stop tied to the western India route.",
  },
  {
    name: "Kagal",
    country: "India",
    continent: "Asia",
    category: "Lived",
    lat: 16.5886465,
    lng: 74.3085454,
    image: "/images/travel/RBD_4.webp",
    note: "A Kolhapur-area stop from the older western India map.",
  },
  {
    name: "IIT Roorkee",
    country: "India",
    continent: "Asia",
    category: "Lived",
    lat: 29.8542626,
    lng: 77.8880002,
    image: "/images/travel/IITR.webp",
    note: "Campus and academic stop in Uttarakhand.",
  },
  {
    name: "Hyderabad",
    country: "India",
    continent: "Asia",
    category: "Lived",
    lat: 17.406498,
    lng: 78.4772439,
    image: "/images/travel/hydrabad.webp",
    note: "Longer southern India base and major city stop.",
  },
  {
    name: "Kannur",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 11.874477,
    lng: 75.370369,
    image: "/images/travel/Kannur.webp",
    note: "Kerala coastal stop from the southern India route.",
  },
  {
    name: "Tirupati",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 13.6845,
    lng: 79.3478,
    image: "/images/travel/Tirupati.webp",
    note: "Temple-town visit in Andhra Pradesh.",
  },
  {
    name: "Madurai",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 9.9252007,
    lng: 78.1197754,
    image: "/images/travel/Madurai.webp",
    note: "Temple city stop from the Tamil Nadu travel set.",
  },
  {
    name: "Kodaikanal",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 10.2391086,
    lng: 77.4977456,
    image: "/images/travel/Kodai.webp",
    note: "Hill-station visit in the Palani hills.",
  },
  {
    name: "Thrissur",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 10.5276416,
    lng: 76.2144349,
    image: "/images/travel/Thrissur.webp",
    note: "Kerala cultural stop from the southern route.",
  },
  {
    name: "Athirapalli",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 10.2907988,
    lng: 76.5155834,
    image: "/images/travel/Athirapalli_1.webp",
    note: "Waterfall visit in Kerala's lush inland stretch.",
  },
  {
    name: "Kanyakumari",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 8.0843512,
    lng: 77.5495019,
    image: "/images/travel/Kanyakumari.webp",
    note: "Southern tip of India stop where the seas meet.",
  },
  {
    name: "Mahabalipuram",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 12.6208,
    lng: 80.1945,
    image: "/images/travel/Mahabalipuram_1.webp",
    note: "Coastal heritage stop near Chennai.",
  },
  {
    name: "Kanchipuram",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 12.834174,
    lng: 79.703644,
    image: "/images/travel/Mahabalipuram_1.webp",
    note: "Historic temple-city visit in Tamil Nadu.",
  },
  {
    name: "Ooty",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 11.41,
    lng: 76.699997,
    image: "/images/travel/Ooty.webp",
    note: "Nilgiri hill-station visit from the southern route.",
  },
  {
    name: "Puducherry",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 11.9415915,
    lng: 79.8083133,
    image: "/images/travel/Pondy.webp",
    note: "Coastal town visit with French-quarter streets.",
  },
  {
    name: "Khandwa",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 21.8314037,
    lng: 76.3497612,
    image: "/images/travel/Khandwa.webp",
    note: "Madhya Pradesh stop from the central India route.",
  },
  {
    name: "Vadodara",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 22.3072,
    lng: 73.1812,
    image: "/images/travel/Vadodara.webp",
    note: "Gujarat city visit connected to western India travel.",
  },
  {
    name: "Ahmedabad",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 23.0225,
    lng: 72.5714,
    image: "/images/travel/Amedabad.webp",
    note: "Major Gujarat stop for architecture, food, and city wandering.",
  },
  {
    name: "Daman",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 20.3974,
    lng: 72.8328,
    image: "/images/travel/Daman.webp",
    note: "Coastal union territory stop on the western route.",
  },
  {
    name: "Gandhinagar",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 23.2156,
    lng: 72.6369,
    image: "/images/travel/Gandhinagar.webp",
    note: "Planned-capital stop near Ahmedabad.",
  },
  {
    name: "Tamiya",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 22.342,
    lng: 78.6703,
    image: "/images/travel/Tamiya.webp",
    note: "Satpura-region hill and forest stop.",
  },
  {
    name: "Indore",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 22.7195687,
    lng: 75.8577258,
    image: "/images/travel/Indore.webp",
    note: "Central India city stop on the Madhya Pradesh loop.",
  },
  {
    name: "Maheshwar",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 22.179298,
    lng: 75.586754,
    image: "/images/travel/Maheshwar.webp",
    note: "Narmada riverfront and historic fort-town visit.",
  },
  {
    name: "Jamboti",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 15.44,
    lng: 74.23,
    image: "/images/travel/Jamboti.webp",
    note: "Western Ghats stop near the Karnataka-Goa border.",
  },
  {
    name: "Gaganbawada",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 16.5457904,
    lng: 73.8311296,
    image: "/images/travel/Gaganbawada.webp",
    note: "Ghat-road and monsoon landscape stop near Kolhapur.",
  },
  {
    name: "Hanuwantiya Tapu",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 22.1448,
    lng: 76.5873,
    image: "/images/travel/Hanuwantiya.webp",
    note: "Reservoir island stop on the Narmada backwaters.",
  },
  {
    name: "Old Goa",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 15.496777,
    lng: 73.827827,
    image: "/images/travel/OldGoa.webp",
    note: "Heritage church and old-capital stop in Goa.",
  },
  {
    name: "Murud Janjira",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 18.299589,
    lng: 72.964425,
    image: "/images/travel/Murud_Janjira.webp",
    note: "Sea-fort and Konkan coast visit.",
  },
  {
    name: "Trimbakeshwar",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 19.9322,
    lng: 73.5308,
    image: "/images/travel/Trimbakeshwar.webp",
    note: "Temple-town stop near Nashik.",
  },
  {
    name: "Saptasrungi Temple",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 20.3914,
    lng: 73.9068,
    image: "/images/travel/Saptasrungi.webp",
    note: "Hilltop temple visit in Maharashtra.",
  },
  {
    name: "Kunkeshwar",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 16.3319,
    lng: 73.3959,
    image: "/images/travel/Kunkeshwar.webp",
    note: "Konkan coastal temple and beach stop.",
  },
  {
    name: "Kudremukha",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 13.1413,
    lng: 75.2537,
    note: "Western Ghats mountain and forest route.",
  },
  {
    name: "Murdeshwar",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 14.094,
    lng: 74.4899,
    note: "Coastal Karnataka temple and sea-view stop.",
  },
  {
    name: "Mangalore",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 12.9141,
    lng: 74.856,
    note: "Port-city stop on the Karnataka coast.",
  },
  {
    name: "Bengaluru",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 12.971599,
    lng: 77.594566,
    note: "Major Karnataka city stop from the southern route.",
  },
  {
    name: "Gokarna",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 14.5479,
    lng: 74.3188,
    note: "Beach and temple-town visit on the west coast.",
  },
  {
    name: "Marleshwar",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 17.0745,
    lng: 73.7362,
    note: "Waterfall and cave-temple stop in the Konkan hills.",
  },
  {
    name: "Ganapatipule",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 17.1489,
    lng: 73.2727,
    note: "Konkan beach and temple-town visit.",
  },
  {
    name: "Tarkarli",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 16.037,
    lng: 73.4848,
    note: "Coastal stop known for beaches and clear water.",
  },
  {
    name: "Sindudurg Fort",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 16.043769,
    lng: 73.461416,
    note: "Sea-fort stop on the Malvan coast.",
  },
  {
    name: "Suvarnadurg Fort",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 17.817,
    lng: 73.085,
    note: "Coastal fort stop on Maharashtra's Konkan route.",
  },
  {
    name: "Raigadh Fort",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 18.2335,
    lng: 73.4407,
    note: "Hill-fort visit tied to Maratha history.",
  },
  {
    name: "Pratapgad Fort",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 17.9371,
    lng: 73.5782,
    note: "Western Ghats fort stop near Mahabaleshwar.",
  },
  {
    name: "Agonda",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 15.0456,
    lng: 73.9889,
    note: "Quiet south Goa beach stop.",
  },
  {
    name: "Shirdi",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 19.7645,
    lng: 74.4762,
    note: "Pilgrimage-town visit in Maharashtra.",
  },
  {
    name: "Pune",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 18.7167,
    lng: 73.7678,
    note: "Major Maharashtra city stop on the western India route.",
  },
  {
    name: "Solapur",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 17.65992,
    lng: 75.906387,
    note: "Deccan city stop from the Maharashtra route.",
  },
  {
    name: "Udupi",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 13.3409,
    lng: 74.7421,
    note: "Coastal Karnataka temple and food stop.",
  },
  {
    name: "Ambala",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 30.3752,
    lng: 76.7821,
    note: "North India transit and city stop.",
  },
  {
    name: "Dindigul",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 10.3624,
    lng: 77.9695,
    note: "Tamil Nadu city stop between larger southern routes.",
  },
  {
    name: "Manipal",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 13.3524,
    lng: 74.7868,
    note: "University-town stop on the Karnataka coast.",
  },
  {
    name: "Horanadu Annapurna Temple",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 13.2767,
    lng: 75.3438,
    note: "Western Ghats temple visit in the Malnad region.",
  },
  {
    name: "Bhojeshwar Temple",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 23.1003,
    lng: 77.5797,
    note: "Historic temple stop near Bhopal.",
  },
  {
    name: "Srikalahasti",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 13.7498,
    lng: 79.6984,
    note: "Temple-town visit in Andhra Pradesh.",
  },
  {
    name: "Kolar",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 13.1362,
    lng: 78.1291,
    note: "Karnataka stop east of Bengaluru.",
  },
  {
    name: "Dhar",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 22.601292,
    lng: 75.302467,
    note: "Historic Madhya Pradesh stop from the central India route.",
  },
  {
    name: "Davangere",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 14.4644,
    lng: 75.9218,
    note: "Central Karnataka city stop.",
  },
  {
    name: "Belgaum",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 15.8497,
    lng: 74.4977,
    note: "North Karnataka city stop close to the Western Ghats.",
  },
  {
    name: "Kozhikode",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 11.2588,
    lng: 75.7804,
    note: "Kerala coastal city stop on the Malabar route.",
  },
  {
    name: "Ballari",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 15.1394,
    lng: 76.9214,
    note: "North Karnataka city stop near the Deccan heritage belt.",
  },
  {
    name: "Panipat",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 29.3909,
    lng: 76.9635,
    note: "Historic Haryana stop on the north India route.",
  },
  {
    name: "Almatti",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 16.3515,
    lng: 75.8795,
    note: "Dam and reservoir stop in northern Karnataka.",
  },
  {
    name: "Mahabaleswar",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 17.9307,
    lng: 73.6477,
    note: "Hill-station stop in the Sahyadri range.",
  },
  {
    name: "Sawantwadi",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 15.9053,
    lng: 73.8213,
    note: "Konkan town stop near the Goa-Maharashtra border.",
  },
  {
    name: "Kankawali",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 16.2655,
    lng: 73.7083,
    note: "Konkan route stop in Sindhudurg district.",
  },
  {
    name: "Malvan",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 16.0631,
    lng: 73.4711,
    note: "Coastal town stop with fort and seafood memories.",
  },
  {
    name: "Sangli",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 16.8524,
    lng: 74.5815,
    note: "Western Maharashtra city stop near the Krishna river.",
  },
  {
    name: "Dharwad",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 15.4589,
    lng: 75.0078,
    note: "North Karnataka city and cultural stop.",
  },
  {
    name: "Bailhongal",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 15.8133,
    lng: 74.8566,
    note: "Belagavi district stop from the northern Karnataka route.",
  },
  {
    name: "Attari Border",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 31.6048,
    lng: 74.5741,
    image: "/images/travel/Mumbai.webp",
    note: "Border ceremony stop near Amritsar.",
  },
  {
    name: "Amritsar",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 31.634,
    lng: 74.8723,
    image: "/images/travel/Mumbai.webp",
    note: "Punjab city visit anchored by the Golden Temple.",
  },
  {
    name: "Haridwar",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 29.9457,
    lng: 78.1642,
    image: "/images/travel/Haridwar.webp",
    note: "Ganga river and pilgrimage stop in Uttarakhand.",
  },
  {
    name: "Bagdogra",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 26.6986,
    lng: 88.3117,
    image: "/images/travel/Bagdogara.webp",
    note: "Gateway stop for the North Bengal and Himalayan route.",
  },
  {
    name: "Kolkata",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 22.5744,
    lng: 88.3629,
    image: "/images/travel/Kolkata.webp",
    note: "Major eastern India city stop on the map.",
  },
  {
    name: "Siliguri",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 26.7271,
    lng: 88.3953,
    image: "/images/travel/Bagdogara.webp",
    note: "North Bengal transit stop toward the hills.",
  },
  {
    name: "Agra",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 27.1767,
    lng: 78.0081,
    image: "/images/travel/Agra.webp",
    note: "Historic city visit anchored by the Taj Mahal.",
  },
  {
    name: "Fatehpur Sikri",
    country: "India",
    continent: "Asia",
    category: "Visited",
    lat: 27.0945,
    lng: 77.6679,
    image: "/images/travel/FS.webp",
    note: "Mughal heritage stop near Agra.",
  },
  {
    name: "Hoboken",
    country: "United States",
    continent: "North America",
    category: "Visited",
    lat: 40.745255,
    lng: -74.034775,
    image: "/images/travel/Hoboken.webp",
    note: "Hudson waterfront stop across from Manhattan.",
  },
  {
    name: "Jena",
    country: "Germany",
    continent: "Europe",
    category: "Visited",
    lat: 50.9271,
    lng: 11.5892,
    image: "/images/travel/Jena.webp",
    note: "Thuringian university-city stop in Germany.",
  },
  {
    name: "Bastei Bridge",
    country: "Germany",
    continent: "Europe",
    category: "Visited",
    lat: 50.9619,
    lng: 14.0732,
    image: "/images/travel/RBD_4.webp",
    note: "Saxon Switzerland landscape and bridge visit.",
  },
  {
    name: "Kutna Hora",
    country: "Czech Republic",
    continent: "Europe",
    category: "Visited",
    lat: 49.9524,
    lng: 15.2687,
    image: "/images/travel/Kutna_Hora.webp",
    note: "Czech heritage-town visit beyond Prague.",
  },
  {
    name: "Ostrava",
    country: "Czech Republic",
    continent: "Europe",
    category: "Visited",
    lat: 49.8209,
    lng: 18.2625,
    image: "/images/travel/Kutna_Hora.webp",
    note: "Eastern Czech city stop from the central Europe route.",
  },
  {
    name: "Auschwitz-Birkenau",
    country: "Poland",
    continent: "Europe",
    category: "Visited",
    lat: 50.0294,
    lng: 19.2055,
    image: "/images/travel/Auschwitz.webp",
    note: "Memorial and historical site visit in Poland.",
  },
  {
    name: "Zakopane",
    country: "Poland",
    continent: "Europe",
    category: "Visited",
    lat: 49.2992,
    lng: 19.9496,
    image: "/images/travel/zakopane.webp",
    note: "Tatra mountain town stop in southern Poland.",
  },
  {
    name: "Krakow",
    country: "Poland",
    continent: "Europe",
    category: "Visited",
    lat: 50.0647,
    lng: 19.945,
    image: "/images/travel/Krakow.webp",
    note: "Polish city break with historic streets and squares.",
  },
  {
    name: "Tallinn",
    country: "Estonia",
    continent: "Europe",
    category: "Visited",
    lat: 59.437,
    lng: 24.7536,
    image: "/images/travel/Tallin_1.webp",
    note: "Baltic capital visit with medieval old-town streets.",
  },
  {
    name: "Mount Pilatus",
    country: "Switzerland",
    continent: "Europe",
    category: "Visited",
    lat: 46.9795,
    lng: 8.2548,
    image: "/images/travel/Switzerland.webp",
    note: "Swiss mountain excursion above Lucerne.",
  },
  {
    name: "Lucerne",
    country: "Switzerland",
    continent: "Europe",
    category: "Visited",
    lat: 47.0502,
    lng: 8.3093,
    image: "/images/travel/Lucerne.webp",
    note: "Lake city stop in central Switzerland.",
  },
  {
    name: "Riga",
    country: "Latvia",
    continent: "Europe",
    category: "Visited",
    lat: 56.9677,
    lng: 24.1056,
    note: "Baltic capital visit on the northern Europe route.",
  },
  {
    name: "Jeddah",
    country: "Saudi Arabia",
    continent: "Asia",
    category: "Visited",
    lat: 21.5292,
    lng: 39.1611,
    image: "/images/travel/Tallin_1.webp",
    note: "Red Sea city stop in Saudi Arabia.",
  },
  {
    name: "Helsinki",
    country: "Finland",
    continent: "Europe",
    category: "Visited",
    lat: 60.1699,
    lng: 24.9384,
    image: "/images/travel/Tallin_1.webp",
    note: "Nordic capital visit paired with Baltic travel.",
  },
  {
    name: "Palace of Versailles",
    country: "France",
    continent: "Europe",
    category: "Visited",
    lat: 48.8049,
    lng: 2.1204,
    image: "/images/travel/Versailles.webp",
    note: "Grand palace and garden stop outside Paris.",
  },
  {
    name: "Rennes",
    country: "France",
    continent: "Europe",
    category: "Visited",
    lat: 48.1173,
    lng: 1.6778,
    image: "/images/travel/Versailles.webp",
    note: "Brittany city stop on the France route.",
  },
  {
    name: "Schwerin",
    country: "Germany",
    continent: "Europe",
    category: "Visited",
    lat: 53.6353,
    lng: 11.4003,
    image: "/images/travel/Schwerin.webp",
    note: "Lake-city and castle visit in northern Germany.",
  },
  {
    name: "Leipzig",
    country: "Germany",
    continent: "Europe",
    category: "Visited",
    lat: 51.3397,
    lng: 12.3731,
    note: "Saxony city stop for culture and urban exploring.",
  },
  {
    name: "Cuxhaven",
    country: "Germany",
    continent: "Europe",
    category: "Visited",
    lat: 53.8593,
    lng: 8.6879,
    image: "/images/travel/Cuxhaven.webp",
    note: "North Sea coastal stop from Hamburg.",
  },
  {
    name: "Cologne",
    country: "Germany",
    continent: "Europe",
    category: "Visited",
    lat: 50.9375,
    lng: 6.9603,
    note: "Rhine city visit anchored by the cathedral.",
  },
  {
    name: "Magdeburg",
    country: "Germany",
    continent: "Europe",
    category: "Visited",
    lat: 52.1132,
    lng: 11.6081,
    note: "Elbe river city stop in eastern Germany.",
  },
  {
    name: "Munich",
    country: "Germany",
    continent: "Europe",
    category: "Visited",
    lat: 48.1351,
    lng: 11.582,
    note: "Bavarian city visit on the southern Germany route.",
  },
  {
    name: "Zugspitze",
    country: "Germany",
    continent: "Europe",
    category: "Visited",
    lat: 47.4211,
    lng: 10.9854,
    note: "Alpine summit stop at Germany's highest point.",
  },
];
